### ISSUE TITLE
qurare_management 관련

### ISSUE THREAD

**Issue by Sn-Kinos** [Mincl/toy_box#1]
제가 스칼라는 안해봐서 보이는 만큼 보았을 때는
qurare inven crawler 데이터 기반으로 큐라레 관련해서 뭔가를 할 수 있는 토이 프로젝트 같아 우선 한번 다운받아보았습니다.

그런데 gitignore 로 몇몇 중요한 부분이 가려진건지
아니면 제가 scala 설치를 잘못한건지
scala 를 몰라서 그러는건지 모르겠지만 작동이 안되네요 ;ㅁ;

가능하다면 코드를 제대로 받아보고 싶습니다.
큐라레 관련해서는 많은 애정을 갖고 있는지라 관심이 있어 글 남깁니다.

**Comment by Mincl** [comment]
@Sn-Kinos 
해당 프로젝트는 README를 보았을때 **[play framework 2.1](https://www.playframework.com/documentation/2.1.x/Home)** 버전을 이용해서 개발된 것으로 보입니다. 하지만 너무 오래된 버전이라 binary download는 지원해주지 않는 것 같습니다. 다른 방법을 찾아야할 것 같네요.

현재 gitignore에는 play framework로 build했을때 생기는 부산물들만 제외하도록 되어있습니다. 따라서 숨겨진 부분이 없이 현재 코드가 전부입니다.

프로젝트 히스토리를 좀 말씀드리자면... 일단 처음에 큐라레 유틸성 웹앱을 목표로 시작을 했었습니다. 그를 위해서 일부 데이터들이 필요해 큐라레 인벤에서 긁어오는 qurare inven crawler를 개발했었구요.
해당 데이터들을 가져와서 개인 덱들을 구성하여 시뮬레이팅을 하려고 하는 원대한 목표를 세웠으나, 무언가의 이유로 그만둔 것으로 보이네요. 사실 너무 오래전 일이라서 어디까지 개발했는지, 왜 그만 두었는지 기억이 잘 안납니다.

많은 도움이 되어드리지 못해서 죄송합니다.

**Comment by Sn-Kinos** [comment]
답변 주셔서 감사드립니다! 한 번 굴려보면서 가지고 놀아보겠슴다
